volumes:
  app_vol:

version: "3.1"
services:
  next_app:
    container_name: next_app
    restart: never
    image: opscale-sharegpt:v1
    env_file:
      - .env.production
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - app_vol:/app
    networks:
      - sharegpt_network

networks:
  sharegpt_network:
    name: sharegpt_network
    external: true
