version: "3.1"
services:
  next_app:
    container_name: next_app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.app
    env_file:
      - .env.production
    ports:
      - "3000:3000"
