volumes:
  sql_vol:

version: "3.1"
services:
  sql_db:
    image: mysql
    container_name: sql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_USER=mysql
      # - MYSQL_PASSWORD=password
      # - MYSQL_DATABASE=sharegpt
    ports:
      - "3306:3306"
    volumes:
      - sql_vol:/var/lib/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    networks:
      - sharegpt_network

networks:
  sharegpt_network:
    name: sharegpt_network