volumes:
  mysql:

version: "3.1"
services:
  mysql:
    image: mysql
    container_name: mysqlprisma
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_USER=mysql
      # - MYSQL_PASSWORD=password
      # - MYSQL_DATABASE=sharegpt
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password

  # app:
  #     container_name: app
  #     restart: always
  #     depends_on:
  #       - mysql
  #     build:
  #         context: ./
  #         dockerfile: Dockerfile.local
  #     env_file:
  #         - .env.local
  #     ports:
  #         - "3000:3000"
  #     volumes:
  #         - ./components:/app/components
  #         - ./lib:/app/lib
  #         - ./pages:/app/pages
  #         - ./prisma:/app/prisma
  #         - ./styles:/app/styles
  #         - ./public:/app/public

