volumes:
  redis_volume:
  sql_vol:

version: "3.1"
services:

  sql_db:
    image: mysql
    container_name: sql_db
    restart: always
    env_file:
      - .env.production
    ports:
      - "3306:3306"
    volumes:
      - sql_vol:/var/lib/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    networks:
      - sharegpt_network

  next_redis:
    image: redis
    env_file:
      - .env.production
    command: "redis-server --requirepass password"
    volumes:
      - redis_volume:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - sharegpt_network

  next_app:
    container_name: next_app
    restart: always
    image: opscale-sharegpt:v1
    depends_on:
      - sql_db
    env_file:
      - .env.production
    networks:
      - sharegpt_network
    ports:
      - "3000:3000"
  
  next_nginx:
    image: nginx
    depends_on:
      - next_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sharegpt_network



networks:
  sharegpt_network:
    name: sharegpt_network

# certbot --nginx -d sharegpt.opscale.io -d www.sharegpt.opscale.io